version: '3.6'
 
# PROJECT
services:
  web:
    restart: always
    build:
        context: ./
        dockerfile: ./web/Dockerfile
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: PROJECT_HOST.test
    expose:
      - "8000"
    volumes:
      - "webdata:/usr/src/app/project/static"
    command: /usr/local/bin/gunicorn -t 5000 -w 1 -b :8000 project:app
    # command: python manage.py run
    depends_on:
      - db
    networks:
      - db_nw
      - web_nw

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - "webdata:/www/static"
    depends_on:
      - web
    networks:
      - web_nw
 
  db:
    restart: always
    build: ./db
    env_file:
      - .env
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - db_nw

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

volumes:
  dbdata:
  webdata:
